import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center gap-3 p-24">
          <h1 className='text-2xl mb-6'><Link href="/">Tarjetas de memorización</Link></h1>
          {children}
        </main>
      </body>
    </html>
  )
}
